from datetime import datetime
from typing import Protocol

from eor_control.domain import PumpStatus


class Pump(Protocol):
    def connect(self) -> None: ...

    def read_status(self) -> PumpStatus: ...

    def request_stop(self) -> None: ...

    def disconnect(self) -> None: ...


class DataAcquisition(Protocol):
    def read_voltage(self, channel: str) -> float: ...

    def write_voltage(self, channel: str, voltage: float) -> None: ...

    def set_safe_state(self) -> None: ...


class Clock(Protocol):
    def utc_now(self) -> datetime: ...

    def monotonic(self) -> float: ...

    def sleep(self, seconds: float) -> None: ...
